In [3]:
 import statsmodels.api as sm
 from statsmodels.tsa.stattools import adfuller
 from statsmodels.tsa.arima.model import ARIMA

In [4]:
ts=sm.datasets.sunspots.load_pandas().data["SUNACTIVITY"]

In [5]:
ts.head()

0     5.0
1    11.0
2    16.0
3    23.0
4    36.0
Name: SUNACTIVITY, dtype: float64

In [7]:
#if it is above 0.05 mean is not constant/non stationery
#if it is below 0.05 mean is constant/ stationery
#in this case the mean is above a small margin so it is okay we can use it
adfuller(ts)[1]

/tmp/ipykernel_1153/3869666928.py:4: FutureWarning: adfuller currently returns a plain tuple whose length depends on the store and autolag arguments. In release 0.16 or after July 2027, whichever is later, the default behavior will switch to always returning an ADFullerResult. Set result_object=True to switch now, or result_object=False to keep the current behavior and silence this warning.
  adfuller(ts)[1]

0.053076421728120673

In [11]:
arima=ARIMA(ts,order=(3,2,4))
model=arima.fit()

/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/statespace/mlemodel.py:679: EstimationWarning: Non-invertible starting MA parameters found. Using zeros as starting parameters.
  start_params = self.start_params
/usr/local/lib/python3.13/dist-packages/statsmodels/tsa/statespace/mlemodel.py:737: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  mlefit = super().fit(

In [12]:
model.aic

np.float64(2580.0354825532086)

In [14]:
model.forecast(steps=5)

309    27.072191
310    56.141399
311    79.300216
312    90.291044
313    85.431404
Name: predicted_mean, dtype: float64